### ISSUE TITLE
安全问题怎么考虑的？

### ISSUE THREAD

**Issue by tanxiaolong** [kennethhutw/sharetable#1]
“1. 报名：立刻填写报名数据
2. 等候：每天收Email期待官方配对通知
3. 联络：透过Email与对方联系用餐时间地点
4. 出发：您可独自或携伴前往赴约用餐！”

恕我多虑，如果有个妹子独自去，安全问题怎么考虑；如果一个男生遇到了仙人跳，安全问题怎么考虑？
仅仅是设计在“人人都是好人”的前提下进行的吗？

**Comment by kennethhutw** [comment]
Yes, It based on "人人都是好人".  But how u define "good man"?
 We are adults so we should know how to protect ourselves and know who is good or bad. 
if you cannot, I will say " hi, growing up!!  "

**Comment by tanxiaolong** [comment]
@kennethhutw   想法有问题，你不能用一句说“我们都是成年人了”来搪塞，那按照你的逻辑，我们都是成年人了，我们都有能力保护自己了，要法律做什么？
或者退一步讲，我们都是成年人了，那你这个产品的初衷就不要那么情怀，那么华丽，直接说吃个饭约个炮，大家也不是说不能接受。你既然想实现你的理想在这个产品里，那么就要考虑更多的东西。按照你的逻辑，我倒更愿意对你说“hi, growing up!!”。

**Comment by kennethhutw** [comment]
@tanxiaolong  I don't know what happened to you. "吃个饭约个炮" why did you think so? 

Yes, Law is a kind of ways to protect people but we should not rely on that. We should learn how to protect ourselves not to expect someone or something will protect us. 

 I may be a idealist and truly believe that people can get together and enjoy a wonderful meal after a hard working day. As I said in readme.md,  I hope people can go to know new people by meal.  If there is chemistry, people can have the second meal or go to explore more interesting restaurants.  In China, most people who leave away from their city and go to work in other cities. Sometime, it is hard to know new friends or hard to have meal with friends at bad time.  So I hope it can provide a way to solve this.
